#!/bin/sh
set -eu
tunnel=wrangler

cloudflared login
cloudflared tunnel create "$tunnel" || :
id=$(cloudflared tunnel info -o json "$tunnel" | jq -r .id)
cloudflared tunnel route ip add 0.0.0.0/0 "$tunnel" || :
cloudflared tunnel route dns --overwrite-dns "$tunnel" "$tunnel.kaipov.com"

token=/tmp/cloudflared-tunnel-$id.json
rm -f "$token"
cloudflared tunnel token --credentials-file "$token" "$tunnel"
config=/tmp/cloudflared-tunnel-$id.config.yml
cat >"$config" <<EOF
url: http://localhost:8787
tunnel: $id
credentials-file: $token
EOF
cloudflared tunnel --config "$config" run "$tunnel"
