#!/bin/sh
set -eu

root=$(git rev-parse --show-toplevel)
repo=$(basename "$root")
log() { printf '\033[1;33m%s\033[0m\n' "$*" >&2; }
get() { op read "op://github/$repo/$1"; }

main() {
        log "Setting up $repo"
        : "${OP_SERVICE_ACCOUNT_TOKEN?needs to be set for op CLI}"
        op user get --me
        devvars kaal-ket-jor >"$root/.dev.vars"
}

devvars() {
        bot=${1?}
        cat <<EOF
DISCORD_APPLICATION_ID: $(get "$bot/app-id")
DISCORD_PUBLIC_KEY: $(get "$bot/public-key")
DISCORD_TOKEN: $(get "$bot/token")
EOF
}

main "$@"
