#!/bin/sh
set -eu

root=$(git rev-parse --show-toplevel)
repo=$(basename "$root")
log() { printf '\033[1;33m%s\033[0m\n' "$*" >&2; }
get() { op read "op://github/$repo/$1"; }

main() {
        log "Setting up $repo"
        : "${OP_SERVICE_ACCOUNT_TOKEN?needs to be set for op CLI}"
        op user get --me
        sync_secrets kaal-ket-jor
}

sync_secrets() {
        name=${1?}
        appid=$(get "$name/app-id")
        pubkey=$(get "$name/public-key")
        token=$(get "$name/token")

        cat >"$root/.dev.vars" <<EOF
DISCORD_APPLICATION_ID: $appid
DISCORD_PUBLIC_KEY: $pubkey
DISCORD_TOKEN: $token
EOF

        secret_put DISCORD_APPLICATION_ID "$appid"
        secret_put DISCORD_PUBLIC_KEY "$pubkey"
        secret_put DISCORD_TOKEN "$token"
}

secret_put() {
        key=$1
        val=$2
        echo "$val" | wrangler --config "$root/wrangler.toml" secret put --name "$name" "$key"
}

main "$@"
