---
name: Go image builder

description: Build Go images

inputs:
  dir:
    description: The name of the dir relative to the Go directory
    required: true
  token:
    description: The GitHub token
    required: true

# https://docs.docker.com/build/ci/github-actions/examples/#registry-cache
runs:
  using: composite
  steps:
  - name: set image name
    shell: bash
    run: |
      echo "path=${{ github.repository }}/go/${{ inputs.dir }}" >>$GITHUB_ENV
  - uses: docker/setup-buildx-action@v3
  - uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ github.repository_owner }}
      password: ${{ inputs.token }}
  - uses: docker/build-push-action@v5
    with:
      push: true
      cache-from: type=registry,ref=ghcr.io/${{ env.path }}:buildcache
      cache-to: type=registry,ref=ghcr.io/${{ env.path }}:buildcache,mode=max
      context: "{{ defaultContext }}:go"
      build-args: |
        dir=${{ inputs.dir }}
        module=github.com/${{ env.path }}
      tags: |
        ghcr.io/${{ env.path }}:latest
