name: Images for Go apps

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
    - go/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/images-for-go-apps
      with:
        dir: chatbot
        token: ${{ secrets.GITHUB_TOKEN }}
